version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-

      - run:
          name: Setup git user
          command: |
            git config --global user.email $MY_EMAIL
            git config --global user.name $MY_NAME

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Run gulp
          command: yarn run publish

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: dependency-cache-{{ checksum "package.json" }}

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
